version: '3.3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer
    ports:
      - 8080:8080

# Comandos para acessar a base
# docker exec -it mysql-db-1 bash -l
# mysql -u root -p